map_type: costmap

obstacle_range: 5.0
raytrace_range: 8.0

transform_tolerance: 0.2

#footprint: [[.4, .15], [.4, -0.15], [-0.4, -0.15], [-0.4,0.15]]
#robot_radius: 0.4 
inflation_radius: 0.3

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /udacity_bot/laser/scan, marking: true, clearing: true}


